### ISSUE TITLE
In Resource Request

### ISSUE THREAD

**Issue by bishaljoshi08** [pshreyam/OS-Works#1]
In resource request I am getting this
![image](https://user-images.githubusercontent.com/52276876/127802458-afd1049d-4cdd-48ba-97df-ef68cb024570.png)
here instead of allocation[1] the value of allocation[4] is being displayed but the final value after addition is correct
Also the numbering is messed up
![image](https://user-images.githubusercontent.com/52276876/127802503-90416243-40af-47ec-b727-968cb19c78a4.png)

**Comment by pshreyam** [comment]
Ok, will fix that!
